import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'
import 'react-data-grid/lib/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ZH-CN" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  )
}
